LuaDoc, version 3.0
Tomas Guisasola (tomas@tecgraf.puc-rio.br)
http://luadoc.luaforge.net
13/aug/2007

What is it?

LuaDoc is a documentation generator tool for Lua source code.
It parses the declarations and documentation comments in a set of Lua
source files and produces a set of XHTML pages describing the commented
declarations and functions.

The output is not limited to XHTML. Other formats can be generated by
implementing new doclets. The format of the documentation comments is
also flexible and can be customized by implementing new taglets.
Please refer to customizing section for further information.

LuaDoc is free software and uses the same license as Lua. 

Distribution:

This distribution includes a set of  Lua  files  and  this  README.  It
requires Lua 5.1.

Installation:

LuaDoc tool is composed by two parts, a library, and a launcher script.

The library follows the package model for Lua 5.1, therefore it should
be "installed".

The launcher script, namely luadoc.lua for Unix and luadoc.bat for Windows,
should be installed in your system PATH, so that it can be executed.

LuaDoc also depends on two external packages: LuaFileSystem and LuaLogging,
and you'll need to install them accordingly.

On Unix boxes, the file luadoc.lua could be used as a script;
it's the same as:

lua5.1 luadoc.lua [options|files]

This is the main script: it will load LuaDoc library and process the
specified files. Try luadoc.lua --help, it will show you all available
options. 

How does it work?

LuaDoc works in two phases: analysis and synthesis.  On the first  one,
all input files are analyzed and an intermediate structure is made with
this information.  The second phase is responsible for  cross-reference
and the composition of the output.  Each phase has an engine  file  and
one or more description files, that describe the source format and  the
output format.  This distribution only have a description of Lua source
files and another for HTML output files.

Some technical documentation can  be  built  running  LuaDoc  over  its
files.

Please send any comments and bug reports to tomas@tecgraf.puc-rio.br

